version: '3.8'

services:

  grpc_server:
    container_name: grpc_server
    image: grpc_server:latest
    build: .
    restart: unless-stopped
    environment:
      GRPC_PORT: 50051
      MAX_WORKERS: 5
    ports:
      - 50090:50051